### ISSUE TITLE
QLog 0.6.0, Settings: Station Location Profiles

### ISSUE THREAD

**Issue by DL2KI** [foldynl/QLog#10]
In the tab "Station" the fields "Callsign" and "Gridsquare" in the "Dark" theme appear empty after selecting the profile, although contents are available. The content is only visible after clicking into the field.

![station_location_profiles_1s](https://user-images.githubusercontent.com/26311402/156999565-b70d8096-21b7-4382-a9c5-72d54b921d3b.jpg)

![station_location_profiles_2s](https://user-images.githubusercontent.com/26311402/156999608-6f9663c6-92a8-4e7b-b429-ed41718ed6b4.jpg)

**Comment by foldynl** [comment]
will be fixed in next release
