### ISSUE TITLE
New QSO callbook data

### ISSUE THREAD

**Issue by DL2KI** [foldynl/QLog#118]
Additional information:

My impression is that the display of the callbook data works much better here when the rig is not connected.
The behavior can be reproduced by connecting and disconnecting the rig.

Possibly this behavior is also related to the Whisperer function when using the bandmap.

**Comment by foldynl** [comment]
Please, could you tested against a new version 0.14.

if your observations are the same, please describe the exact problem

**Comment by DL2KI** [comment]
Callsign selection via the bandmap now works in version 0.14.
Data from the callbook is displayed immediately. The issue can be closed.

**Comment by foldynl** [comment]
Thank you for your confirmation.
