### ISSUE TITLE
QLog 0.6.0, DX Cluster

### ISSUE THREAD

**Issue by DL2KI** [foldynl/QLog#12]
- In the DX cluster I mainly use "telnet.reversebeacon.net:7000" for CW. For users who prefer other DX clusters, it would be useful to store some "DXC Server address" entries so that you can select them from the menu.

- For example, if one enters an incorrect "telnet.**x**reversebeacon.net:7000" entry in the field, and then deletes the "x" by pressing the "DEL" key, the entire entry is deleted.

- The input field for the "DXC Server address" is narrow when empty. If you enter "telnet.reversebeacon.net:7000" there and then press "Connect", the input field remains narrow and does not adapt in width to the content. This only happens when you confirm the entry of the "DXC Server address" with "Enter".

**Comment by foldynl** [comment]
> * In the DX cluster I mainly use "telnet.reversebeacon.net:7000" for CW. For users who prefer other DX clusters, it would be useful to store some "DXC Server address" entries so that you can select them from the menu.

You can simple add a new server by typing server name directly to the Combobox. If QLog can connect the server then the server hostname is  saved for later usage



> * For example, if one enters an incorrect "telnet.**x**reversebeacon.net:7000" entry in the field, and then deletes the "x" by pressing the "DEL" key, the entire entry is deleted.

I know what you mean. I did not want to design a new windows where DXC server will be defined. Therefore I guess that it will be useful to make a setting via Editable Combo where it will be possible to delete an entry by simply pressing the DEL key. Unfortunately, It seems that it is not a good design.

Will be fixed

> * The input field for the "DXC Server address" is narrow when empty. If you enter "telnet.reversebeacon.net:7000" there and then press "Connect", the input field remains narrow and does not adapt in width to the content. This only happens when you confirm the entry of the "DXC Server address" with "Enter".

Will be fixed

**Comment by DL2KI** [comment]
> You can simple add a new server by typing server name directly to the Combobox. If QLog can connect the server then the server hostname is saved for later usage.

Thanks, you are right, it works like this. But here only if the existing entry is selected and the new server name is entered directly over the existing entry. 

If the existing entry is marked in the combo box and first deleted with "DEL" to get an empty input field, only the last entered server name is taken. 

So: my mistake when entering the server name, or a thinking error on my part. But now I know how it works.

**Comment by foldynl** [comment]
I can see that DXC server Combobox is misleading. I'll try to remake it somehow.

What do you think what is better. 
1) To stay with the same concept (DXC is directly defined via Combobox), but to change DEL shortcut to another keyboard shortcut (example CTRL+DEL)
2) Add a DXC servers  definition to the Setting Dialog (I don't like this option very much, because it expands the dialog)  

Are you able to test the source code directly from the test branch or you are use only installation packages?

**Comment by DL2KI** [comment]
I think that this could be left as it is, if the "correct" way of input is noted in a future help text. 

Whether a change of the DEL shortcut key brings an improvement, you would have to test yourself once. The extension of the settings dialog is then not necessary, which also rather corresponds to your ideas.

Cloning and compiling the testing branch I have already tried here. This works without any problems.

**Comment by foldynl** [comment]
I tried to remake it. Maybe it will be better. I am preparing a "repair" release. 

Fixed is already in Testing branch.
