### ISSUE TITLE
CW settings, model "Morse Over CAT"

### ISSUE THREAD

**Issue by DL2KI** [foldynl/QLog#121]
If you select Model "Morse Over CAT" in the CW settings, the "Key Mode" can no longer be changed. The "Key Mode" must be set here before the model selection. A subsequent change (Edit, Modify) is also not possible. 

The effect only occurs with this model.

**Comment by foldynl** [comment]
As I know, Key mode is not possible to change via CAT. It can be set only via transceiver. Therefore Key mode is ignored (disabled) when Morse Over CAT is selected - the selection has no impact on the setting of Morse CAT

[QLog Wiki:](https://github.com/foldynl/QLog/wiki/Initial-Setup#cw-keys)

* **Key Mode** - currently supported key modes are: Single Paddle, Iambic A/B, Ultimate. The Key Mode is reflected only in case of **Winkey** model.

**Comment by DL2KI** [comment]
OK, sorry. I had not checked that before.
So the issue can be closed.
