### ISSUE TITLE
Equipment" menu

### ISSUE THREAD

**Issue by DL2KI** [foldynl/QLog#122]
"Connect CW Keyer" is the first item in the Equipment menu. Then "Connect Rig" and "Connect Rotor" follow.

From my point of view "Connect Rig" should be at the top of the list, because this item is used most often. If the Key Profile has been specified in the Rig settings, only this list entry must be selected.

If you don't use CW mode, the entry "Connect Rig" would also be better at the first position of the list.

**Comment by foldynl** [comment]
OK...no problem. I will change it in a next version.
