### ISSUE TITLE
CW Console, Wiki

### ISSUE THREAD

**Issue by DL2KI** [foldynl/QLog#123]
> The operator can define CW Key profiles that can be switched via a combo box in the upper left corner. The combo box in the right bottom corner is used to select currently used shortcuts profile.

The combo box for the shortcut profiles is not located in the lower right corner, but at the top, to the right of the combo box for the CW Key profiles.

**Comment by foldynl** [comment]
Thank you very much. 

I unified the GUI at the last moment and did not update the WIKI page

WIKI has been updated. Closing the issue
