### ISSUE TITLE
OSM-Map, Layer-menu

### ISSUE THREAD

**Issue by DL2KI** [foldynl/QLog#127]
In the layer menu of the OSM map, it probably needs to be "Grid" instead of "Grip".

![Screenshot_20221012_160359](https://user-images.githubusercontent.com/26311402/195365491-8b79a3c1-f7d0-4295-a948-3cba4161b9b7.png)

**Comment by foldynl** [comment]
I look at it every time it starts and I don't see it. Thanks for your report.
