### ISSUE TITLE
WWFF is not downloaded correctly

### ISSUE THREAD

**Issue by foldynl** [foldynl/QLog#169]
WWFF CSV format changed, QLog must be prepared for it.

**Comment by dwh367** [comment]
WWFF is not downloading correctly again. Linux Mint Xia.

**Comment by aa5sh** [comment]
Looks like their website (wwff.co) is down:

![Image](https://github.com/user-attachments/assets/860cafb7-7335-4829-a5e8-159d4c13b967)
