### ISSUE TITLE
Centering the online map

### ISSUE THREAD

**Issue by dl2ki** [foldynl/QLog#185]
Would it be an idea to center the OnlineMap on the gridsquare set in the selected station profile when starting QLog?

Thereby the OnlineMap could be enlarged to a zoom level of about 5 (from the largest map display press "Zoom in" 5 times), which would give a sufficiently accurate overview of the location. This would provide additional information to the user without having to change anything in the GUI.
 
The disadvantage of this would be that the global position of the grayline in the smallest zoom level would not be directly visible when QLog is started.
 
So one would have to weigh which information would be more useful to the standard user when starting QLog. Global position of the grayline or centering on the own location.

**Comment by foldynl** [comment]
A part of release 0.20
