### ISSUE TITLE
Rig widget, Band and Mode menu

### ISSUE THREAD

**Issue by dl2ki** [foldynl/QLog#187]
In the Rig widget, when the current seleted band or mode is in the lower list area in the "Band" and "Mode" combo box menus, the list expands upwards, beyond the frame of the main window.

![Screenshot_20230310_113249](https://user-images.githubusercontent.com/26311402/224300429-3c3186c8-46c3-458f-b07f-8af6dda07890.png)  ![Screenshot_20230310_113325](https://user-images.githubusercontent.com/26311402/224300448-fe0b4637-37a9-4970-8081-5ed00c0d7a96.png)

No particular problem arises from this. You can also arrange different windows outside the main window. However, the question arises whether parts of the controls of any software should extend beyond the main window. Normally the main window should define the area in which a program is executed.

The selection menus in the filter area behave similarly.

This is just a general reference to a behavior of some menus that I noticed. I cannot judge whether changes are useful or necessary here. It does not affect the operation of QLog.

**Comment by foldynl** [comment]
It is default behavior of ComboBox in QT. 

I don't see any problem with displaying the ComboBox content outside the main window if there is space. Personally, I don't know how exactly it should behave when the last item is selected and it is necessary to display this list in order, but I will try to see if there is another solution. 

It is possible to add Scrollbar on the left/right side but  I don't think it will bring anything clear.

**Comment by dl2ki** [comment]
I would rather leave it as it is, since it does not affect the function. If there is not enough space at the top, the selection list moves to the bottom. With long lists (filter, country) the entries can be scrolled.

From my point of view, the issue can be closed.
