### ISSUE TITLE
Text alignment Name, QTH in NewQSO

### ISSUE THREAD

**Issue by dl2ki** [foldynl/QLog#189]
If a callsign is entered in the NewQSO area that is already included in the log and has a long text in the QTH field, this text is not displayed left-aligned. This is also the case for very long names.

![Screenshot_20230313_110127](https://user-images.githubusercontent.com/26311402/224674437-8dbe5c03-7eac-4710-9dcf-0bd7e1afc045.png)

In the example the complete text in the QTH field is `"Preussisch Oldendorf - Bad Holzhausen"`.

If the fields are left-justified, you could cut off the text at the right end of the field, or additionally replace the last 3-4 characters in the visible area of the field with dots.

Whether other input fields are affected, was not checked further.

**Comment by foldynl** [comment]
Yeah, I know about it. Already reported in #157 
Postponed for now. I tried some variants, but it was not user-friendly. The variant you described with the shortening is interesting, but it is needed to think about the fact that the fields as a whole must behave in these situations

1) the field is not focused
2) the field has a focus
3) the field is edited
4) Edit mode finished

etc.

**Comment by dl2ki** [comment]
oh, sorry for the double issue. I noticed that again this morning.

In the future I have to look more closely whether there was already a report on this.

**Comment by foldynl** [comment]
no problem.
