### ISSUE TITLE
Some anomalies in the input and processing of " QSLr Date"

### ISSUE THREAD

**Issue by dl2ki** [foldynl/QLog#192]
Yesterday I got some new QSL cards, and entered the data in QLog.

For the first time I used the field "QSLRDATE" and entered the date in "Edit-Mode". In the field "Paper, Received" you can enter a date. The default in "Edit-Mode" is "02.01.00".

![Screenshot_20230408_090301](https://user-images.githubusercontent.com/26311402/230708507-ee47cf4f-c9a3-44aa-aa06-4f1b06efd2c0.png)

The default for "Edit Value" in the QSO list is "31.12.99". 

![Screenshot_20230408_090555](https://user-images.githubusercontent.com/26311402/230708511-954d30a4-436e-46fb-8e93-a595cf0b3e3c.png)

In "Edit-Mode" the input of the year is limited to 2 digits. Therefore I entered the date "07.04.23" in the field "Paper, Received". 

![Screenshot_20230408_081804](https://user-images.githubusercontent.com/26311402/230708718-14cc1eb9-0a24-4929-881b-8f5f389c6cad.png)

In the QLog database the date appears as "07.04.1923".

![Screenshot_20230408_081920](https://user-images.githubusercontent.com/26311402/230708813-919cba06-85e1-4d77-8f69-dbb1cfe41eb7.png)

If I accept the default date "31.12.99" in the QSO list with "Edit Value", 

![Screenshot_20230408_092856](https://user-images.githubusercontent.com/26311402/230709461-40d2bb01-f270-4382-8208-d4de5b222871.png)

this value appears in the QLog database:

![Screenshot_20230408_092953](https://user-images.githubusercontent.com/26311402/230709470-5fc37fb5-5a97-40e4-ae0a-34e750d246a1.png)

I can neither delete this date in the QSO list with "Edit Value", nor in the "Edit-Mode".

The pictures represent examples. Other manual entries in date fields have not yet been further checked.

**Comment by foldynl** [comment]
in general, it is not recommended to use the date in the YYMMDD format after the year 2000,  for the reason you are sending now.  The year format is controlled by the environment settings. Therefore, it will be necessary to change your environment settings to the year format YYYYMMDD.

**Comment by dl2ki** [comment]
My attempts to change the date format to 4-digit years were unsuccessful. I have not found a way to set this under Kubuntu 22.04.

According to my research, it is no longer possible to change the date format with KDE5. It is fixed in the "Locales".

I also haven't noticed yet that entering 4-digit year numbers is not possible in other programs. Programs like "KOrganizer" display the date correctly.

![Screenshot_20230417_184729](https://user-images.githubusercontent.com/26311402/232555417-acb7cb05-1ba8-4c36-8315-25efeea57f34.png)

Therefore I cannot understand at the moment why QLog only allows 2-digit year numbers.

**Comment by foldynl** [comment]
just for tracking the issue. EN locale has a shortDate year in format YYYY but DE locale has the shortDate year in format YY what caused the issue. QLog does not use the longDate format because it contains a lot of additional information. It seems so. that shortDate is very compact for QLog usage.

**Comment by dl2ki** [comment]
Yes, but I have no idea about the internal structures in KDE, Plasma or QT applications.

Anyway, with 2-digit years, for example, you can't use "Date Range" in the statistics window either. 
I don't use these date fields at the moment. But in the database the dates of the QSO's are correct, so I can use QLog!

![Screenshot_20230418_104232](https://user-images.githubusercontent.com/26311402/232723999-cb82a026-200e-469b-bc23-9da63e448946.png)

![Screenshot_20230418_104315](https://user-images.githubusercontent.com/26311402/232724016-a2a7b228-dcb1-47b5-b474-40fe383e3fcd.png)

![Screenshot_20230418_104346](https://user-images.githubusercontent.com/26311402/232724030-85c9a69d-52ce-44c7-944a-e591cafd6e7b.png)

Perhaps a solution to the problem will be found later.
