### ISSUE TITLE
DX Cluster and Alert Rules Filter

### ISSUE THREAD

**Issue by dl2ki** [foldynl/QLog#210]
In the band settings there are many bands that can be activated or deactivated.

However, in "Alert-Rule-Detail" there are only the bands 160m to 6m, which can be activated if required. This corresponds to the filter settings of the DX-Clusters window.

The cluster "telnet.reversebeacon.net" I use, also evaluates CQ calls in the 4m and 2m band.

![Screenshot_20230610_171812](https://github.com/foldynl/QLog/assets/26311402/793ccd80-11b5-4d76-a04f-4036c4380c1b)

Other DX clusters evaluate additional bands.

![Screenshot_20230610_172142](https://github.com/foldynl/QLog/assets/26311402/58e91ab9-c269-40b3-acb1-ed1e572cae8c)

Since I use here only the HF bands this question is not relevant for me and I noticed it only by chance if i activate no bands in "Alert-Rule-Detail".

But if someone wants to participate in a VHF/UHF contest by example, he has no possibilities to set a corresponding filter in the DX-Custer or in the Alert-Rules.

One solution would be to be able to select the filters from the band pool that are enabled in the band settings.
Maybe there are also other useful solutions.

**Comment by foldynl** [comment]
The bands for DXC Filter and Aler Rules Windows are derived from setting - the bands are activated in Settings->Bands.

In my opinion, it is not possible to show all bands in these "small" windows - there are too many bands. The operator must choose which one he/she wants to prefer and then set them in Setting->Bands. 

If you want to watch 4/2m bands then you have to activate them in the Setting.
