### ISSUE TITLE
Multi language Support

### ISSUE THREAD

**Issue by dl2ki** [foldynl/QLog#219]
The wiki lacks examples for use on Windows and Mac OS.

**Comment by foldynl** [comment]
please, could you specify what is missing in the description? The map language is controlled the same way as the GUI language.

**Comment by dl2ki** [comment]
Sorry. I meant the wiki page "Multi language Support".

Here is an example how to start QLog with a different language translation.

> The language can also be set manually via OS's locales. An example below shows how the language can be changed manually to Czech via OS environment setting (Linux):
> 
> LANGUAGE=cs.CZ.UTF-8 ./qlog

My thought was that a Windows or Mac OS user might also need an example. Since I don't use Windows or Mac OS I can't say anything more about this.

**Comment by foldynl** [comment]
Wiki has been updated.Closing issue.
