### ISSUE TITLE
Qlog on MacOS Catalina 10.15

### ISSUE THREAD

**Issue by xfailed** [foldynl/QLog#224]
Hello, would there be hope to see Qlog working on Catalina MAC OS 10.15 ? I have a fairly old mac mini and can't install MACOS 12

**Comment by CutePotatoDev** [comment]
From time to time i building for 10.13.6. May be it works for you to. Can share compiled binary.

**Comment by xfailed** [comment]
Ah yes it would be nice to be able to test that. You can send me a sharing link or send me a wetransfer to the following address cuille.joel@orange.fr

**Comment by xfailed** [comment]
ah oui ce serait sympa de pouvoir tester ça. Vous pouvez m'envoyer un lien de partage ou me faire un wetransfert à l'adresse suivante f4jkl@orange.fr

**Comment by CutePotatoDev** [comment]
Please. 
https://www.pastefile.com/1et3vr
Share result, work or not.

**Comment by xfailed** [comment]
THANKS ! I recovered the file but unfortunately it does not work. Nothing happens when I run it. No error message.

**Comment by CutePotatoDev** [comment]
Yes, my mistake. i just send you plain .app without proper preparation.
Now looks like i prepare it with proper build process. It's same zipped .app but i more or less follow this:
https://github.com/foldynl/QLog/blob/master/.github/workflows/macOSBuild.yml
Hope it works.

0.25.1 -> https://www.pastefile.com/cnp1nn

**Comment by xfailed** [comment]
oops ! I let the tick pass. I did not come early enough to retrieve the file, it is no longer online.
