### ISSUE TITLE
Add user define button for callsign lookup

### ISSUE THREAD

**Issue by foldynl** [foldynl/QLog#230]
### Discussed in https://github.com/foldynl/QLog/discussions/229

<div type='discussions-op-text'>

<sup>Originally posted by **liathit** July 24, 2023</sup>
Please add user define button for callsign lookup. Cqrlog have that feature that very comfortably

![Screenshot from 2023-07-24 09-06-16](https://github.com/foldynl/QLog/assets/1136932/cfd11145-4eb7-49ab-b962-f1e453e3a377)

![Screenshot from 2023-07-24 09-07-08](https://github.com/foldynl/QLog/assets/1136932/ca83ef3f-25da-4da9-bb89-e19f846b0a31)
</div>

**Comment by liathit** [comment]
Thank you))

**Comment by foldynl** [comment]
that was a good idea, it's wrong to prefer the certainty service. It is needed to have an option.
