### ISSUE TITLE
Incorrect WSJTX locator target on map.

### ISSUE THREAD

**Issue by CutePotatoDev** [foldynl/QLog#237]
When callsign arriving from wsjtx online map showing it's location incorrectly, usually overshooting random distance. But looks like targeting correct country.  
When checking logged "QSO Details" everything is OK there.

**Comment by CutePotatoDev** [comment]
Test from branch testing_0.27. Everything works like charm.

**Comment by foldynl** [comment]
Perfect. Many thanks for testing and confirmation.
