### ISSUE TITLE
Possibility to change details layout.

### ISSUE THREAD

**Issue by CutePotatoDev** [foldynl/QLog#243]
Hello.
It's be nice to have possibility to edit "Details" tab layout. Remove unwanted fields from details tab. And unwanted tabs.

![Screen Shot 2023-09-05 at 21 09 05](https://github.com/foldynl/QLog/assets/2453573/cfaa497f-4bf1-4014-9502-c8c315a37153)

**Comment by foldynl** [comment]
The tabs remain as is but the Details tab will be editable in the future. It is one of the reasons why Layout feature was introduced.

**Comment by foldynl** [comment]
release v0.29 implements this
