### ISSUE TITLE
pfx field

### ISSUE THREAD

**Issue by ik3ocd** [foldynl/QLog#263]
good morning from flavio ik3ocd these days I'm trying your qlog work and a nice project, I noticed that the import from other logs is successful and all the fields are ok, but upon a new QSO insertion the information for the prefix in the pfx field seems to be missing , perhaps not yet implemented, the pfx information on QSO insertion is also missing. Thanks for any response on this. 73'

my kde 39 operating system
​
![pfx](https://github.com/foldynl/QLog/assets/151148789/2094f903-2441-4ed5-8ac3-2e662ad1f537)

**Comment by foldynl** [comment]
Currently, It is not yet implemented. QLog only accept the PFX from external sources (WSJTX, import etc).

But it is easy to add it. It will be a part of next release.

**Comment by ik3ocd** [comment]
grazie foldynl ,Thanks for your reply, I like your work and I look forward to further qlog progress. ciao e 73 de ik3ocd flavio
