### ISSUE TITLE
'detached' window won't 'attach'

### ISSUE THREAD

**Issue by foldynl** [foldynl/QLog#268]
Tested and it seems that impacted platforms are QT 5.1x under wayland and Flatpak under wayland.

Temporary solution described in the discussion #266 

### Discussed in https://github.com/foldynl/QLog/discussions/266

<div type='discussions-op-text'>

<sup>Originally posted by **g7kse** November 21, 2023</sup>
Probably something really daft but I managed to detach the dx cluster window and went to re attach it and can't seem to do it. Now its floating as a second window. 

I know its something really simple but I've had it floating for days now and can't seem to get it back...please someone put me out of my shame :-)

![image](https://github.com/foldynl/QLog/assets/13124178/f5c2ac90-e00b-43b3-b7fe-7389e297bc69)
</div>

**Comment by foldynl** [comment]
flatpak is prepared without Wayland support. https://github.com/flathub/io.github.foldynl.QLog/pull/4

**Comment by g7kse** [comment]
Sorted, works with flatpak thanks

**Comment by foldynl** [comment]
excellent.  

it seems Wayland will be a nightmare for me. QT is not properly prepared for it
