### ISSUE TITLE
Bandmap 60m

### ISSUE THREAD

**Issue by DL2KI** [foldynl/QLog#27]
When switching on the 60m band, the band start is displayed in the band map at 5.102 kHz. In the IARU, region 1, the band start is at 5.3515 kHz.

**Comment by foldynl** [comment]
you can edit the starting value via `Setting` -> `Bands` by double-clicking on the field. Unfortunately, there is an issue (#36) where you can enter only 2 decimal places. Issue #36 will be fixed in the next release.
