### ISSUE TITLE
Band Changer

### ISSUE THREAD

**Issue by DL2KI** [foldynl/QLog#29]
The Band Changer in the Rig Widget does not work for me. 
No band selection is offered.

**Comment by foldynl** [comment]
Does it occur for your K2 or K3? Band Changer is filled from hamlib - it was quite reliable when I tested it

**Comment by DL2KI** [comment]
Hi,

The effect occurs with both the K3 and the K2. The dropdown menu has no content.

![image](https://user-images.githubusercontent.com/26311402/162586253-3bf059aa-bfeb-42f1-a99c-4e40de2f64f0.png)

**Comment by foldynl** [comment]
I am sorry. You talked about the Band Changer. It is  not filled from from hamlib but from the profile setting. Do you have defined TX range in the Rig Profile? Setting-> Equipment-> Rig and for the profile field TX Range 0 - 30MHz? I wanted to fill it from hamlib but some rigs have  sub-variants and it is not easy to recognize which sub-variant you use. Therefore the operator has to define the range for particular rig manually. 
![image](https://user-images.githubusercontent.com/942769/162587549-2b2f0927-5c1e-4c02-a19a-a4a4d38bcb6b.png)

**Comment by DL2KI** [comment]
Oh, sorry. Thanks for the info.

Now the band selection works. I had overlooked that in the wiki.
