### ISSUE TITLE
Voice keyer feature required

### ISSUE THREAD

**Issue by BG7JAF** [foldynl/QLog#290]
Hi foldynl:

It's nice to have a voice keyer when doing contest or POTA activation, will you consider add this feature to qlog?

**Comment by foldynl** [comment]
Hi,

from README file
```
This log is not currently focused on contests.
```

As stated in README, this is not a contest log application. In fact, I like to attend contests, reworking Qlog into a contest log would be an incredible job. Even now, after 2 years of development, Qlog is still not where I'd like to see it - day-to-day log.

Your idea is nice, but I don't think it will be implemented in the near future. There are many must-have things with higher priority but only one developer with limited time. 

But I'll leave it as opened with "nice to have" label.
