### ISSUE TITLE
Not possible to enter a Satellite QSO

### ISSUE THREAD

**Issue by ea5wa** [foldynl/QLog#291]
Is not possible to enter a satellite QSO, because there is no satname and satmode fields (or better with a list)

![image](https://github.com/foldynl/QLog/assets/54686689/3501adff-4f1c-4bcf-bdf3-2ac2daec6275)

**Comment by foldynl** [comment]
There are the SAT fields. QLog field layout was changed in 0.29 when Sat-Tab was removed and newly you can define own layout with sat fields via Layout->Edit->Add. The SAT field are `SAT Mode` and `SAT Name`.

**Comment by ea5wa** [comment]
Hi Ladislav, thanks for your answer.

I've done it, I've added satname and Satmode to the layout but I can not put focus on these fields and therefore I can't write on them

![image](https://github.com/foldynl/QLog/assets/54686689/b7d1fafa-1078-437c-ab55-83de70576017)

**Comment by foldynl** [comment]
Did you change `Propagation Mode` to `Satellite`? 

I have the same layout for testing and everything is working. See below.

![sat](https://github.com/foldynl/QLog/assets/942769/6cc2fa27-f682-4f24-ad7e-6ba0e7ee3b23)

**Comment by ea5wa** [comment]
Ok. That's the problem....

On the Mode's list I can't see the correct mode for QO-100 satellite. It should be S/X. Is it possible to edit that list?

**Comment by foldynl** [comment]
Ok. it is clear to me now. Unfortunately, the list is built-in therefore it has to be fixed.

**Comment by ea5wa** [comment]
Thanks 73

**Comment by foldynl** [comment]
BTW. It seems that SAT_MODE field is an optional field. It means that it does not have to be filled for a valid QSO. Based on [LoTW](https://lotw.arrl.org/lotw-help/satellite-qsos/?lang=en) and [eQSL](https://www.eqsl.cc/qslcard/eSatelliteRules.cfm) service specification, the valid Sat QSO must contain Propagation mode = 'SAT' and valid Sat Name.

However, it does not change the fact that SX will be added to QLog. I think that correct source of the Sat modes can be this [link](https://www.pe0sat.vgnet.nl/satellite/sat-information/modes/).

**Comment by ea5wa** [comment]
Then, are you going to remove that list (satmode)? Or is better to have all the possibilities in that list? From my point of view, for a satellite QSO is interesting to have RX frequency or RX band visible. A satellites dropdown list is useful

**Comment by foldynl** [comment]
> Then, are you going to remove that list (satmode)? Or is better to have all the possibilities in that list?
> 
SX will be added to QLog. Sat mode remains as is.

> From my point of view, for a satellite QSO is interesting to have RX frequency or RX band visible. A satellites dropdown list is useful

correct me if I'm wrong, but the QO-100 RX/TX offset has a constant value. This means that you just need to enter the correct RIT/XIT offset for your rig in QLog and you will see the correct frequencies in the QLog. Sorry, I don't have a lot of SAT experience, if there can be a situation where the RX and TX frequency offset will not have a fixed value or it will change non-linearly. In this case, QLog would not be able to record the correct frequency.

**Comment by ea5wa** [comment]
I understand RIT/XIT use in the same band, but normally satellites has uplink/downlink in different bands

**Comment by foldynl** [comment]
I am sorry. I wanted to say RX/TX Offset in the Rig setting dialog

![image](https://github.com/foldynl/QLog/assets/942769/c119a02f-1f62-4b3b-a5bc-1431c4bd1301)
 
Otherwise RX/TX freq is displayed when Manual Mode is enabled.

**Comment by ea5wa** [comment]
Not useful for sats. Just some of them like GreenCube

**Comment by foldynl** [comment]
if we neglect the doppler effect, then it is usable. Yes, SPLIT mode would be better. It is planned.

**Comment by ea5wa** [comment]
I always neglect doppler efect. Just simply introduce the frequency (and band) for Uplink and the frequency (and band) for Downlink for that QSO. Normally, I take these frequencies from a satellites list. These images are taken from KLog (the soft I've been using until now):

![image](https://github.com/foldynl/QLog/assets/54686689/a05e92f2-6175-4865-9f4a-136036a11ba3)
![image](https://github.com/foldynl/QLog/assets/54686689/b929502d-41c4-4b29-ab71-1c86fcff045e)
