### ISSUE TITLE
No SunSDR support

### ISSUE THREAD

**Issue by RobbiePh** [foldynl/QLog#300]
I have tried several radio in rig control but none with display the proper modes?

DUSB on the rig is RTTY on the software.

 I am using the SunSDR2 .

Back to Log4OM, I think for the moment.

De Ei2iP

**Comment by foldynl** [comment]
possible solutions are present in my comment [#299 ](https://github.com/foldynl/QLog/discussions/299#discussioncomment-8106046)

**Comment by RobbiePh** [comment]
Found a work around, thanks. TCI Logger installed.

![image](https://github.com/foldynl/QLog/assets/96705124/4a07e13f-7fc0-4e99-b230-bbe0f9550e67)

**Comment by foldynl** [comment]
I'm glad it worked out. I would like to ask. I have no experience with SunSDR, but I looked at the TCI spec and it's not complicated. But it will be necessary to test it. Is there any SunSDR simulator software?
