### ISSUE TITLE
FT4 is displayed as MFSK

### ISSUE THREAD

**Issue by RobbiePh** [foldynl/QLog#303]
So when JTDX logs qso, the qso in QLog is logged as MFSK rather than FT4. Would it be possible to add FT4 to the list of modes?

De Ei2iP, Robbie

![image](https://github.com/foldynl/QLog/assets/96705124/f04a790e-a47e-4838-a90d-db1f145bd3c0)

![image](https://github.com/foldynl/QLog/assets/96705124/f4481eef-7b62-4906-a745-f30b8c2a5cd2)

**Comment by foldynl** [comment]
It was explained in [#296](https://github.com/foldynl/QLog/issues/296#issuecomment-1867300025)
