### ISSUE TITLE
Filter contact records table by station

### ISSUE THREAD

**Issue by ra3sad** [foldynl/QLog#312]
Please add filter for contacts table to select it by station name/callsign.

**Comment by foldynl** [comment]
You can define your own User-defined [filter](https://github.com/foldynl/QLog/wiki/Main-Window#qso-filters)

**Comment by ra3sad** [comment]
I found nothing about Station in user defined filters. It would be nice and very usefull for multi operator stations to add a dropdown list with station profile names at first position (to the left of BAND combo box)
Thanks, Alex.

**Comment by ra3sad** [comment]
It works, tnx!

**Comment by foldynl** [comment]
perfect
