### ISSUE TITLE
E-QSLs since 

### ISSUE THREAD

**Issue by ik3ocd** [foldynl/QLog#341]
Good evening  . could it be possible to download the request in e-qsl mode by date or by last request like in lotw?
Thank you .
![e-qsl since](https://github.com/foldynl/QLog/assets/151148789/71a87402-dd19-463e-bba2-59842c0f2730)

**Comment by foldynl** [comment]
Based on [eQSL Spec](https://www.eqsl.cc/QSLcard/DownloadInBox.txt), it is possible.

**Comment by ik3ocd** [comment]
Thank you for your consideration.
