### ISSUE TITLE
Omnirig CW/CWR mode

### ISSUE THREAD

**Issue by foldynl** [foldynl/QLog#347]
Based on the email from  ZL3AB:

1. I have a Kenwood TS590SG which I control using its ARCP software.  Using Qlog with Omnirig v1 allows me to connect Qlog to the rig at the same time. I have noticed in the Rig window that it shows the rig being in CW reverse (CWR) when it is in CW mode.  Also If I click on a station in the bandmap the rig QSYs to that frequency and but puts the rig into CWR.  It is not a big deal as I can simply change it back but it is annoying.

**Comment by foldynl** [comment]
I will need some advice here. I've read a few discussions about the cw/cwr difference on different rigs, but It is not clear to me. Maybe you, as more experienced operator, can advise me.

Situation is as follows. QLog does the translation from internal mods to rig mods. In the case of the Omnirig, QLog CW mode translates to Omnirig CW_L (it's internal Omnirig mode - means CW "LSB") and CWR to CW_U (means "USB").

I have an IC7300, where in the case of CW_L, a command for CW "Normal" is sent and CW_U switches to "CWR". I looked at the Omnirig command definition for TS590SG, and these commands are swapped. CW_U sends a command for CW and CW_L sends a command for "CWR". That's it works for me and not for you.

Please, could you tell me, as an experienced person, what is Normal CW and what is CWR? Is Normal CW = CW_U and CWR = CW_L or is it reversed?

 
Based on this, it will either be necessary to modify the QLog and Omnirig init file, or only the Omnig init file.

**Comment by ik3ocd** [comment]
hi, if it can be useful to you, normally on my rtx yaesu ftdx 3000 the cw is received on the usb cw combination, i.e. on a frequency higher than that of the carrier. in the case of an interfering signal you can try switching to the reverse cw i.e. to the cw lsb combination to direct the interfering signal out of the medium frequency pass band.

**Comment by foldynl** [comment]
Thanks. It confirms my assumptions from reading articles. It was also mentioned in articles that CW "USB" is normal "CW" and CWR is CW "LSB". I'll try to wait to see if there are any other opinions. 

however, under these conditions, the Omnirig definition for IC7300 is incorrect and QLog also has an internal translation issue.

**Comment by foldynl** [comment]
maybe the situation is not as clear as I think. I am attaching a part of  email from ZL3AB :

```
On the CW issue and as you have said, it appears Yaesu and Icom use LSB (CW-L) 
by default for CW and Kenwood uses USB on CW (CW-U) by default.

Therefore in Kenwood's world normal CW is CW_U and CWR is CW_L. 
For Yaesu and Icom it is the other way around.
```

QLog definitely shouldn't go down the path of a new settings. The workaround is to change the Omnirig init file, but this may affect other Hamradio applications.
