### ISSUE TITLE
ADIF-Import

### ISSUE THREAD

**Issue by DL2KI** [foldynl/QLog#35]
In "Discussions - Import of ADIF data from other programs " you wrote:

> Therefore I decides to implement following algorithm.
> 
> If QLog imports ADIF file with NAME field then it is saved to QLog's NAME_INTL field (without any conversion), because it can contain , incorrectly, UTF-8 characters from source application.
> 
> QLog tries to remap accents string to accent-less string and save it to NAME field. This field is marked as NAME (ASCII) and it is strictly used for ADI export.

When I save two test QSO's, the names and QTH's are saved in the NAME / NAME_INTL and QTH / QTH_INTL fields as described above.

See the first two log entries.

![Eingabe Test-QSO](https://user-images.githubusercontent.com/26311402/162606189-ff41673f-3931-4a62-9c45-0f920dddcc21.png)

Then in QLog I deleted the existing log and re-imported the current ADI file from CQRLog. Now here you can see that the import of the fields NAME / NAME_INTL and QTH / QTH_INTL is not done as described above.

![ADIF-Import](https://user-images.githubusercontent.com/26311402/162606222-b94abd01-e8bd-4ec6-af46-9c2550618251.png)

Most of the NAME_INTL and QTH_INTL fields are empty.

**Comment by foldynl** [comment]
Please, could you share a ADIF record(s) (file) for the QSOs where the fields are missing?

**Comment by DL2KI** [comment]
Hi,

here are the logbook excerpts:

```
cqrlog_adif-test.adi.zip:     Logbook extract from CQRLog
testlog.png:                  image of the records

testlog-export.adi.zip:       adi export from QLog
testlog-export.adx.zip:       adx export from QLog
testlog-export.json.zip:      json export from QLog
```
[cqrlog_adif-test.adi.zip](https://github.com/foldynl/QLog/files/8458652/cqrlog_adif-test.adi.zip)

![testlog](https://user-images.githubusercontent.com/26311402/162611609-1d8d490c-ee31-4185-adbb-bca2b460f3c8.png)

[testlog-export.adi.zip](https://github.com/foldynl/QLog/files/8458656/testlog-export.adi.zip)
[testlog-export.adx.zip](https://github.com/foldynl/QLog/files/8458657/testlog-export.adx.zip)
[testlog-export.json.zip](https://github.com/foldynl/QLog/files/8458658/testlog-export.json.zip)

**Comment by foldynl** [comment]
my apologies, my mistake. It seems that I did not "commit" the patch. I will fix it in the next release.
