### ISSUE TITLE
Question marks are silently removed from entries

### ISSUE THREAD

**Issue by p14e** [foldynl/QLog#350]
Hi,

first I must say QLog is an awesome logging program and I like it very much. Keep up the good work!

I'm using QLog 0.34 (commit 5f8bf45bf9) compiled directly from the git-sources.

I just noticed that QLog silently modifies or even completely removes ADIF-tags containing a question mark ("?"). I imported an ADIF-log containing a comment-tag like "foobar ?" and some other field containing only a single "?", then I added some info like gridsquares to several log-entries and exported the full log as .ADI and .ADX. After that I noticed by pure chance that the question-mark disappeared from the comment-tag (it now reads just "foobar ") and the tags with the single question mark were completely gone.

I hope this can be fixed soon.

Thanks & Best Regards,
Patrick

**Comment by p14e** [comment]
Hi,

I can confirm commit 9b861669db fixes the issue. I'm looking forward to the next release. :-)

Thanks for fixing it!

Best Regards,
Patrick

**Comment by foldynl** [comment]
the next release will hopefully be soon. It will not use commit https://github.com/foldynl/QLog/commit/9b861669dbd451c7e5443dd22fe87a0cdf48d0fe but commit https://github.com/foldynl/QLog/commit/65fc34bbe7a1c8b803ff06683cc4d357d77e57fd . There was an issue under Windows

please be careful when using these devel commits. I don't recommend test them if you don't know what you are doing (more  #361)
