### ISSUE TITLE
Can't connect to k3ng keyer

### ISSUE THREAD

**Issue by BG7JAF** [foldynl/QLog#367]
k3ng keyer can simulate as winkey v2, so I tried to connect QLog to a k3ng keyer using 1200 baudrate, but the connection failed. I have also try n1mm+ and fldigi and both them can work with that k3ng keyer, so I think maybe it's QLog's problem?

73

**Comment by foldynl** [comment]
I am also using the K3NG Keyer as WinKey v2 Keyer without any issue. It is one of my test cases to use K3NG as Winkey. Your setting seems to be correct. It is important to have setting described here:

**Comment by foldynl** [comment]
Please send me your K3NG Keyer version?

**Comment by BG7JAF** [comment]
Hi foldynl,

My k3ng keyer's version is  "2024.03.20.2239"
After disable automatic software reset(I just add a big capacitor between RESET and GND), I can connect k3ng keyer with QLog now.  Thank you very much!

73
