### ISSUE TITLE
Bandmap select previous selected callsign issue

### ISSUE THREAD

**Issue by dimarmnes** [foldynl/QLog#394]
QLog 0.36
Manjaro Linux Flatpak

After selecting a callsign in the bandmap, the frequency and callsign field in the new qso form changes correctly.  If I change the frequency and try to select the previous selected callsign in the bandmap, nothing happens.  Does not fill the field in new qso or change frequency.

[Grabación de pantalla desde 2024-06-27 19-01-04.webm](https://github.com/foldynl/QLog/assets/168468132/12de261b-811c-4b8e-8c47-6161c5722d0a)

**Comment by foldynl** [comment]
yes, I know about the problem. It is  a workaround for other thing, but as a side effect is that the same Callsign is not tuned again. I'll try to work on it.
