### ISSUE TITLE
Alert window enhacement - Alert Dock Widget

### ISSUE THREAD

**Issue by foldynl** [foldynl/QLog#399]
### Discussed in https://github.com/foldynl/QLog/discussions/397

<div type='discussions-op-text'>

<sup>Originally posted by **TecnoTalarn** July  1, 2024</sup>
![image](https://github.com/foldynl/QLog/assets/61935185/3f91e74c-7b2c-4518-a65a-b13681ebaac7)
I don't know if it would be possible for the alert window to be included in the layout so that when you start the software it stays in the desired position? As you can see in the picture.

by the way, where I can help with the translation of the program?</div>

**Comment by TecnoTalarn** [comment]
Thanks! 

look well
