### ISSUE TITLE
WSJT-X integration - mode setting

### ISSUE THREAD

**Issue by gtorino** [foldynl/QLog#402]
During a FT8 QSO and also on registering it, QLog doesn't take Mode information ("FT8") from WSJT-X, but holds that one taken from the rig ("SSB/USB"). I have to manually edit later the registered QSO replacing "SSB" with "FT8". "Accept UDP requests" on WSJT-X is checked. QLog 0.37.0

**Comment by gtorino** [comment]
The only way to make QLog recording the correct information is activating "Enable logged contact ADIF broadcast" on WSJT-X:
![image](https://github.com/foldynl/QLog/assets/18402703/8a5b1bf5-1566-4967-9cdf-cfbfd14958fb)

So I have:
![image](https://github.com/foldynl/QLog/assets/18402703/0aef1f52-1284-4f87-826e-e7437025b0ab)

But the mode displayed remains uncorrect:
![image](https://github.com/foldynl/QLog/assets/18402703/f30bf6e5-765a-4a7f-b431-8aa5ec341dd2)

**Comment by foldynl** [comment]
unfortunately I tested now I can't confirm this. The Mode is taken from the WSTJX Log Message and is independent of what the QLog shows. It means that if a request for inserting a QSO comes from WSJTX, the correct mode/submode is saved. The fact that ADIF is on or off does not determine this either. It is necessary not to save QSOs from digital mods using Save QSO in QLog, but using messages from external messages. it is done automatically in the case of WSJTX after every successfully completed QSO.

**Comment by gtorino** [comment]
Thanks a lot Ladislav for the very clear explanation. That's also my experience in effect.
