### ISSUE TITLE
New Window "Details"

### ISSUE THREAD

**Issue by OZ1CT-Ben** [foldynl/QLog#407]
would it be possible tom make a new "Windows" whit a "Details" ???

I think the info in "Details" is somthing you use when you setup the log, so my idea was to make it turn on/off if you need it. for my reason it will give me more space on the dashboard for Cluster-Rotor-Chat to use this place ???

![Qlog-Details](https://github.com/foldynl/QLog/assets/26863044/cc34b455-079e-4a66-917a-c0b4200919d7)

73" OZ1CT Ben

**Comment by foldynl** [comment]
Unfortunately, getting possible to switch on/off this window is not as simple as it might seem at first. It is part of the NewContact window. This would mean redesigning the entire NewContact function, which would also have a negative impact on Layout Settings and other parts of QLog. The negatives outweigh the positives of the change.

**Comment by OZ1CT-Ben** [comment]
Ok...then this idea is grounded 😉

73" Ben

Send from my mobile office.

man. 8. jul. 2024 10.12 skrev Ladislav ***@***.***>:
