### ISSUE TITLE
Callsign Context Menu

### ISSUE THREAD

**Issue by dl2ki** [foldynl/QLog#409]
When I select the callsign in the "Callsign" field, the "Cut", "Copy", and "Delete" menu options do not work.

![Screenshot_20240709_081405](https://github.com/foldynl/QLog/assets/26311402/9dbf55ad-abe1-4235-9a3b-99b17387a202)

**Comment by foldynl** [comment]
thanks. it is interesting that the shortcuts CTRL+C, V etc are working
