### ISSUE TITLE
Position and zoom factor of the bandmap

### ISSUE THREAD

**Issue by dl2ki** [foldynl/QLog#415]
I noticed the following:

Example:

You set the bandmap to 40m so that the beginning of the band is visible at the top.

![Screenshot_20240719_082056](https://github.com/user-attachments/assets/6a9fa433-1c44-4c4c-8e8a-01eeecee135b)

 Now you switch to e.g. 20m and set the bandmap so that the end of the band is visible at the bottom.

![Screenshot_20240719_082134](https://github.com/user-attachments/assets/b494fc4f-de13-42b9-bc04-d01b538938a4)

If you now switch back to 40m, the bandmap has lost its original position and the end of the band is displayed. 

![Screenshot_20240719_082153](https://github.com/user-attachments/assets/a0127613-d862-44ea-aaad-4b61d74bd027)

Would it make sense to temporarily save the bandmap settings (scroll position, zoom factor) for each band so that they can be restored when switching bands?

**Comment by foldynl** [comment]
The zoom factor is now saved. The scroll position is not saved, which is a good idea. I have enabled `Center RX`, so I always have the same position because QLog saves the "last seen frequency before band switching." However, if you have disabled` Center RX`, the scroll position can vary.
