### ISSUE TITLE
Improvement Idea: Integrate Alert Window within Main Application Window

### ISSUE THREAD

**Issue by oh2gba** [foldynl/QLog#419]
The "alert" window currently opens as a separate desktop window. Instead, integrate the alert window within the main application to streamline the interface. 

At least for me, this window is important / very useful, but it ends up behind the main window. The small bell icon just doesn't get the attention. 

The "beep" is nice, and helps a bit. However I usually have the "system alert sounds" off, as they tend to be annoying.

**Comment by foldynl** [comment]
It has already been requested as issue #399. I am closing this issue as duplicate.
