### ISSUE TITLE
Antenna Follows Band 

### ISSUE THREAD

**Issue by VK4IM** [foldynl/QLog#437]
Hi
 
In settings under the equipment section it is possible to enter antenna profiles. Thank you.
 
When entering contacts in the main window there is an option to select the antenna in use under the "My Station" tab.
 
My request is as follows:
 
Please provide an option (check box) to allow the antenna to follow the radio. Having a check box to "Opt In" will allow greater scope for operator efficiency.
 
To clarify:  When the radio is on 10m then the antenna in "My Station" automatically follows and reads the correct antenna from the "Antenna Profiles" section in setup. The same occurs when changing to any other band.
 
73
Adam VK4IM

![2](https://github.com/user-attachments/assets/6e4f38d9-9971-48e4-a13e-78c3c19cc82e)
![1](https://github.com/user-attachments/assets/efa7d600-b0d1-477a-92c8-6245d23f47b7)

**Comment by foldynl** [comment]
generally in #392. 

the problem with your improvement is that the antenna profile must have the same name as the band. #392 should solve this more generally.
