### ISSUE TITLE
Where is the Qlog Database located?

### ISSUE THREAD

**Issue by Javier-EA6ALW** [foldynl/QLog#439]
Hi! Thanks for you work in this log.

I'm wondering if I could have a copy of the database of my log in order to store it on my cloud. With that I can have secure backup if my PC fails. Where can I find the database? if so, can Qlog backup itself every 1 day or so?

Hope I explain myself. English is not my first language.

Thank you in advance.
73

**Comment by foldynl** [comment]
see [QLog Wiki Autobackup](https://github.com/foldynl/QLog/wiki/Autobackup) for details . It is better to backup ADX autobackup files.
