### ISSUE TITLE
ADIF import does not import records with old DXCC Entities

### ISSUE THREAD

**Issue by foldynl** [foldynl/QLog#459]

**Comment by ik1vqy** [comment]
Good morning
Restarting from the previous post, I have found that if I save in QLog some Old Entities and I export the log in adif file, when I import the same file in QLog, of course after having cleaned the log, the errors are marked again and the records are not imported...

**Comment by ik1vqy** [comment]
Hi Ladislav

I have downloaded the new release 0,39.

Wonderful, it works very very well for me, NO ERRORS. WOW!!

Many Thanks

Best 73's de IK1VQY
