### ISSUE TITLE
HamQTH dx Cluster error

### ISSUE THREAD

**Issue by lishengyou0521** [foldynl/QLog#475]
![image](https://github.com/user-attachments/assets/4d0436cf-eef9-4401-bb5b-a4d6d6ec8de5)
when i use qlog, always show this alert in the picture,it likes dx cluster has been closed,how to fix this error?

**Comment by foldynl** [comment]
I'm sorry, but I don't understand what the dialog is showing. Can you translate it into English?

If you're having a problem with the HamQTH DXC connection, you can use others as well - see [Wiki DXC](https://github.com/foldynl/QLog/wiki/DX-Cluster)

**Comment by lishengyou0521** [comment]
the dialog messages is cannot connected to dxc server,and the reason is host has been closed this connection

**Comment by foldynl** [comment]
I would try to define some other, local DX Cluster.

**Comment by lishengyou0521** [comment]
ok,i try it latter
