### ISSUE TITLE
New function

### ISSUE THREAD

**Issue by BI6NSL** [foldynl/QLog#477]
![image](https://github.com/user-attachments/assets/8f550ef3-ba99-42c3-9c2c-683b5d1c3393)

Is it possible to add such functionality to the page?
To identify the frequency bands and modes in which the call sign has been operated and confirmed.
thank you

**Comment by aa5sh** [comment]
I like this idea.  I think it would be nice to have something like this maybe:
<img width="880" alt="image" src="https://github.com/user-attachments/assets/f457fdef-1ee5-4906-a287-65b6807b82fa">

**Comment by foldynl** [comment]
Gentlemen,

Could you please provide a use case for this change? What is the reason or motivation for implementing it? The only reason I can think of is a DX Expedition. However, it seems to me that this table will be empty most of the time and, as a result, will take up unnecessary space in the GUI. Additionally, if you have the callsign, QLog already displays all QSOs for the given callsign. This allows the operators to see that they already have  QSOs with this station and check the status of those QSOs.

**Comment by aa5sh** [comment]
Primary easy use case if for DX Expeditions like you say.  In my typically layout of QLog I only see about 2-3 previous QSOs depending on the device I use.  So I it is nice to quickly see a summary of previous QSOs.  But I also do work a lot of similar stations on FT8, FT4 on various bands.  That was one feature I missed from RumLogNG.  I do like the way you have the summary laid out better, I could never remember on RL which of the dots meant what.  It is not a have to have feature but it is interesting as I am working to see I’ve worked that station on 5 or more bands, without have to scroll up/down and look at bands/modes etc.

**Comment by aa5sh** [comment]
Just for visual reference this is how I normally have it laid out.  And you can see this station I have had the pleasure to work 26 times.  
![image](https://github.com/user-attachments/assets/b116a028-244a-4446-8490-52ee5c965754)

**Comment by BI6NSL** [comment]
![qlog](https://github.com/user-attachments/assets/7b2efcbe-9ef8-43e5-bf0f-76e093098af6)

Although the list can scroll to see the Qsos that have worked, and the Qsos that have been confirmed, it is not graphically intuitive, and I often get confused about what frequencies and modes I have worked on the station, and which ones I have not worked on.
Avoid too many repetitive Qsos.
If you can hope that you can adopt the suggestion!
Thank you
DE BI6NSL Junxi

**Comment by Down168** [comment]
> Just for visual reference this is how I normally have it laid out. And you can see this station I have had the pleasure to work 26 times. ![image](https://private-user-images.githubusercontent.com/84428382/374627974-b116a028-244a-4446-8490-52ee5c965754.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NDk2MzIsIm5iZiI6MTcyODQ0OTMzMiwicGF0aCI6Ii84NDQyODM4Mi8zNzQ2Mjc5NzQtYjExNmEwMjgtMjQ0YS00NDQ2LTg0OTAtNTJlZTVjOTY1NzU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDA0NDg1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0Yzk5NzFkNzI4M2U0ZDdmMTE5NTQ1Y2JhMjRmMTc3MWY2ZTcwOWE4MDNkNjI3YjkyY2Y5NWEwYmE3NmZkMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XkQOnGS8rGuL9uthfv0ur9G8WuoiVLD4q-Yhr8x0RYk)

Although we know the number of passes , but we can't visualize the specific bands of this site's passes, the above two mentioned features, it is recommended to add to the new version, you can visualize the passes of the bands, modes, and the site's wave patterns, thank you.

**Comment by foldynl** [comment]
To be honest, I don't think it should be included in the release at the moment. I'll take some time to think about it.

**Comment by BI6NSL** [comment]
![image](https://github.com/user-attachments/assets/fcf0c62c-15b1-47bb-aff2-76b044227514)
