### ISSUE TITLE
Suggestion - QSL Import detail text should be selectable.

### ISSUE THREAD

**Issue by BI6NSL** [foldynl/QLog#484]
![image](https://github.com/user-attachments/assets/03812dda-c45c-4fa0-b7a6-53dd77ec9fd5)

It is recommended to make the contents of this box replicable, or export the txt to somewhere.
The user checks the cause of the mismatch one by one

**Comment by aa5sh** [comment]
I was thinking the same thing this morning.  I had several fall into the unmatched section due to duplicate QSOs within the 30 minutes threshold.  But I couldn't copy and past this information so that I could then manually update those as being confirmed.  Had to do a screenshot like above.

**Comment by foldynl** [comment]
The Upload and Download dialogs will change significantly. I will take your comments into consideration.
