### ISSUE TITLE
Hamlib 4.5.5 on Ubuntu 24.04

### ISSUE THREAD

**Issue by vazquezrodjoel** [foldynl/QLog#487]
Last week I upgrade my computer to Ubuntu 24.04 and also updates Hamlib to 4.5.5.  Qlog did not worked with radio.  I had to lower Hamlib to 4.5.4 and now is connecting fine.  

Before downgrading hamlib I grap a debug (hope I did it fine):

`QT_LOGGING_RULES=qlog.rig.*=true qlog
16:16:20.211 [DEBUG   ] [0x7235370eda40]                    [qlog.rig.rig.function.entered] => *** [Rig::Rig(QObject*):rig/Rig.cpp:24] 
16:16:20.212 [DEBUG   ] [0x72351aa006c0]                    [qlog.rig.rig.function.entered] => *** [void Rig::start():rig/Rig.cpp:164] 
16:16:20.869 [DEBUG   ] [0x7235370eda40]                    [qlog.rig.rig.function.entered] => *** [static qint32 Rig::getNormalBandwidth(const QString&, const QString&):rig/Rig.cpp:54] 
16:16:20.870 [DEBUG   ] [0x7235370eda40]                    [qlog.rig.rig.function.entered] => *** [void Rig::setFrequency(double):rig/Rig.cpp:390] 
16:16:20.870 [DEBUG   ] [0x7235370eda40]                 [qlog.rig.rig.function.parameters] => 0 [void Rig::setFrequency(double):rig/Rig.cpp:392] 
16:16:20.871 [DEBUG   ] [0x7235370eda40]                    [qlog.rig.rig.function.entered] => *** [void Rig::setMode(const QString&, const QString&):rig/Rig.cpp:444] 
16:16:20.871 [DEBUG   ] [0x7235370eda40]                 [qlog.rig.rig.function.parameters] => "AM" "" [void Rig::setMode(const QString&, const QString&):rig/Rig.cpp:446] 
16:16:20.871 [DEBUG   ] [0x72351aa006c0]                    [qlog.rig.rig.function.entered] => *** [void Rig::setModeImpl(const QString&, const QString&):rig/Rig.cpp:458] 
16:16:20.871 [DEBUG   ] [0x72351aa006c0]                 [qlog.rig.rig.function.parameters] => "AM" "" [void Rig::setModeImpl(const QString&, const QString&):rig/Rig.cpp:460] 
16:16:20.871 [DEBUG   ] [0x72351aa006c0]                             [qlog.rig.rig.runtime] => Waiting for Rig mutex [void Rig::setModeImpl(const QString&, const QString&):rig/Rig.cpp:462] 
16:16:20.872 [DEBUG   ] [0x72351aa006c0]                             [qlog.rig.rig.runtime] => Using Rig [void Rig::setModeImpl(const QString&, const QString&):rig/Rig.cpp:462] 
16:16:20.894 [DEBUG   ] [0x7235370eda40]                    [qlog.rig.rig.function.entered] => *** [void Rig::setMode(const QString&, const QString&):rig/Rig.cpp:444] 
16:16:20.894 [DEBUG   ] [0x7235370eda40]                 [qlog.rig.rig.function.parameters] => "CW" "" [void Rig::setMode(const QString&, const QString&):rig/Rig.cpp:446] 
16:16:20.894 [DEBUG   ] [0x72351aa006c0]                    [qlog.rig.rig.function.entered] => *** [void Rig::setModeImpl(const QString&, const QString&):rig/Rig.cpp:458] 
16:16:20.894 [DEBUG   ] [0x72351aa006c0]                 [qlog.rig.rig.function.parameters] => "CW" "" [void Rig::setModeImpl(const QString&, const QString&):rig/Rig.cpp:460] 
16:16:20.894 [DEBUG   ] [0x72351aa006c0]                             [qlog.rig.rig.runtime] => Waiting for Rig mutex [void Rig::setModeImpl(const QString&, const QString&):rig/Rig.cpp:462] 
16:16:20.894 [DEBUG   ] [0x72351aa006c0]                             [qlog.rig.rig.runtime] => Using Rig [void Rig::setModeImpl(const QString&, const QString&):rig/Rig.cpp:462] 
16:16:20.895 [DEBUG   ] [0x7235370eda40]                    [qlog.rig.rig.function.entered] => *** [void Rig::setMode(const QString&, const QString&):rig/Rig.cpp:444] 
16:16:20.895 [DEBUG   ] [0x7235370eda40]                 [qlog.rig.rig.function.parameters] => "CW" "" [void Rig::setMode(const QString&, const QString&):rig/Rig.cpp:446] 
16:16:20.895 [DEBUG   ] [0x72351aa006c0]                    [qlog.rig.rig.function.entered] => *** [void Rig::setModeImpl(const QString&, const QString&):rig/Rig.cpp:458] 
16:16:20.895 [DEBUG   ] [0x72351aa006c0]                 [qlog.rig.rig.function.parameters] => "CW" "" [void Rig::setModeImpl(const QString&, const QString&):rig/Rig.cpp:460] 
16:16:20.895 [DEBUG   ] [0x72351aa006c0]                             [qlog.rig.rig.runtime] => Waiting for Rig mutex [void Rig::setModeImpl(const QString&, const QString&):rig/Rig.cpp:462] 
16:16:20.895 [DEBUG   ] [0x72351aa006c0]                             [qlog.rig.rig.runtime] => Using Rig [void Rig::setModeImpl(const QString&, const QString&):rig/Rig.cpp:462] 
16:16:20.896 [DEBUG   ] [0x7235370eda40]                    [qlog.rig.rig.function.entered] => *** [static qint32 Rig::getNormalBandwidth(const QString&, const QString&):rig/Rig.cpp:54] 
16:16:20.896 [DEBUG   ] [0x7235370eda40]                    [qlog.rig.rig.function.entered] => *** [void Rig::setFrequency(double):rig/Rig.cpp:390] 
16:16:20.896 [DEBUG   ] [0x7235370eda40]                 [qlog.rig.rig.function.parameters] => 2.101e+07 [void Rig::setFrequency(double):rig/Rig.cpp:392] 
16:16:20.896 [DEBUG   ] [0x72351aa006c0]                    [qlog.rig.rig.function.entered] => *** [void Rig::setFrequencyImpl(double):rig/Rig.cpp:403] 
16:16:20.896 [DEBUG   ] [0x72351aa006c0]                 [qlog.rig.rig.function.parameters] => 2.101e+07 [void Rig::setFrequencyImpl(double):rig/Rig.cpp:405] 
16:16:20.896 [DEBUG   ] [0x72351aa006c0]                             [qlog.rig.rig.runtime] => Waiting for Rig mutex [void Rig::setFrequencyImpl(double):rig/Rig.cpp:407] 
16:16:20.896 [DEBUG   ] [0x72351aa006c0]                             [qlog.rig.rig.runtime] => Using Rig [void Rig::setFrequencyImpl(double):rig/Rig.cpp:407] 
16:16:21.162 [DEBUG   ] [0x72351aa006c0]                    [qlog.rig.rig.function.entered] => *** [void Rig::update():rig/Rig.cpp:173] 
16:16:21.162 [DEBUG   ] [0x72351aa006c0]                             [qlog.rig.rig.runtime] => Waiting for rig mutex [void Rig::update():rig/Rig.cpp:175] 
16:16:21.162 [DEBUG   ] [0x72351aa006c0]                             [qlog.rig.rig.runtime] => Updating Rig [void Rig::update():rig/Rig.cpp:182] 
16:16:21.295 [DEBUG   ] [0x7235370eda40]                    [qlog.rig.rig.function.entered] => *** [void Rig::setFrequency(double):rig/Rig.cpp:390] 
16:16:21.295 [DEBUG   ] [0x7235370eda40]                 [qlog.rig.rig.function.parameters] => 136000 [void Rig::setFrequency(double):rig/Rig.cpp:392] 
16:16:21.295 [DEBUG   ] [0x72351aa006c0]                    [qlog.rig.rig.function.entered] => *** [void Rig::setFrequencyImpl(double):rig/Rig.cpp:403] 
16:16:21.295 [DEBUG   ] [0x72351aa006c0]                 [qlog.rig.rig.function.parameters] => 136000 [void Rig::setFrequencyImpl(double):rig/Rig.cpp:405] 
16:16:21.295 [DEBUG   ] [0x72351aa006c0]                             [qlog.rig.rig.runtime] => Waiting for Rig mutex [void Rig::setFrequencyImpl(double):rig/Rig.cpp:407] 
16:16:21.295 [DEBUG   ] [0x72351aa006c0]                             [qlog.rig.rig.runtime] => Using Rig [void Rig::setFrequencyImpl(double):rig/Rig.cpp:407] 
16:16:21.295 [DEBUG   ] [0x7235370eda40]                    [qlog.rig.rig.function.entered] => *** [const QStringList Rig::getAvailableRawModes():rig/Rig.cpp:656] 
16:16:21.295 [DEBUG   ] [0x7235370eda40]                             [qlog.rig.rig.runtime] => Waiting for Rig mutex [const QStringList Rig::getAvailableRawModes():rig/Rig.cpp:658] 
16:16:21.295 [DEBUG   ] [0x7235370eda40]                             [qlog.rig.rig.runtime] => Using Rig [const QStringList Rig::getAvailableRawModes():rig/Rig.cpp:658] 
16:16:22.113 [DEBUG   ] [0x72351aa006c0]                    [qlog.rig.rig.function.entered] => *** [void Rig::update():rig/Rig.cpp:173] 
16:16:22.113 [DEBUG   ] [0x72351aa006c0]                             [qlog.rig.rig.runtime] => Waiting for rig mutex [void Rig::update():rig/Rig.cpp:175] 
16:16:22.113 [DEBUG   ] [0x72351aa006c0]                             [qlog.rig.rig.runtime] => Updating Rig [void Rig::update():rig/Rig.cpp:182] 
16:16:23.063 [DEBUG   ] [0x72351aa006c0]                    [qlog.rig.rig.function.entered] => *** [void Rig::update():rig/Rig.cpp:173] 
16:16:23.063 [DEBUG   ] [0x72351aa006c0]                             [qlog.rig.rig.runtime] => Waiting for rig mutex [void Rig::update():rig/Rig.cpp:175] 
16:16:23.063 [DEBUG   ] [0x72351aa006c0]                             [qlog.rig.rig.runtime] => Updating Rig [void Rig::update():rig/Rig.cpp:182] 
16:16:24.013 [DEBUG   ] [0x72351aa006c0]                    [qlog.rig.rig.function.entered] => *** [void Rig::update():rig/Rig.cpp:173] 
16:16:24.013 [DEBUG   ] [0x72351aa006c0]                             [qlog.rig.rig.runtime] => Waiting for rig mutex [void Rig::update():rig/Rig.cpp:175] 
16:16:24.013 [DEBUG   ] [0x72351aa006c0]                             [qlog.rig.rig.runtime] => Updating Rig [void Rig::update():rig/Rig.cpp:182] 
16:16:25.002 [DEBUG   ] [0x72351aa006c0]                    [qlog.rig.rig.function.entered] => *** [void Rig::update():rig/Rig.cpp:173] 
16:16:25.003 [DEBUG   ] [0x72351aa006c0]                             [qlog.rig.rig.runtime] => Waiting for rig mutex [void Rig::update():rig/Rig.cpp:175] 
16:16:25.003 [DEBUG   ] [0x72351aa006c0]                             [qlog.rig.rig.runtime] => Updating Rig [void Rig::update():rig/Rig.cpp:182] 
16:16:25.170 [DEBUG   ] [0x7235370eda40]                    [qlog.rig.rig.function.entered] => *** [void Rig::open():rig/Rig.cpp:210] 
16:16:25.170 [DEBUG   ] [0x72351aa006c0]                    [qlog.rig.rig.function.entered] => *** [void Rig::openImpl():rig/Rig.cpp:217] 
16:16:25.171 [DEBUG   ] [0x72351aa006c0]                             [qlog.rig.rig.runtime] => Waiting for Rig mutex [void Rig::openImpl():rig/Rig.cpp:219] 
16:16:25.171 [DEBUG   ] [0x72351aa006c0]                             [qlog.rig.rig.runtime] => Using Rig [void Rig::openImpl():rig/Rig.cpp:219] 
16:16:25.171 [DEBUG   ] [0x72351aa006c0]                    [qlog.rig.rig.function.entered] => *** [void Rig::__openRig():rig/Rig.cpp:225] 
16:16:25.171 [DEBUG   ] [0x72351aa006c0]                    [qlog.rig.rig.function.entered] => *** [void Rig::__closeRig():rig/Rig.cpp:344] 
16:16:25.171 [DEBUG   ] [0x72351aa006c0]                             [qlog.rig.rig.runtime] => Driver is not active [void Rig::__closeRig():rig/Rig.cpp:348] 
16:16:25.171 [DEBUG   ] [0x72351aa006c0]                             [qlog.rig.rig.runtime] => Opening profile name:  "991A" [void Rig::__openRig():rig/Rig.cpp:239] 
16:16:25.171 [DEBUG   ] [0x72351aa006c0]                    [qlog.rig.rig.function.entered] => *** [GenericRigDrv* Rig::getDriver(const RigProfile&):rig/Rig.cpp:620] 
16:16:25.171 [DEBUG   ] [0x72351aa006c0]                             [qlog.rig.rig.runtime] => 1 [GenericRigDrv* Rig::getDriver(const RigProfile&):rig/Rig.cpp:624] 
16:16:25.171 [DEBUG   ] [0x72351aa006c0]       [qlog.rig.driver.hamlibdrv.function.entered] => *** [HamlibRigDrv::HamlibRigDrv(const RigProfile&, QObject*):rig/drivers/HamlibRigDrv.cpp:125] 
initrigs4_dummy: _init called
yaesu: initrigs4_yaesu called
initrigs4_icom: _init called
initrigs4_icmarine: _init called
initrigs4_pcr: init called
initrigs4_aor: _init called
initrigs4_jrc: _init called
initrigs4_uniden: _init called
initrigs4_drake: _init called
initrigs4_lowe: _init called
initrigs4_racal: _init called
initrigs4_wj: _init called
initrigs4_skanti: _init called
initrigs4_winradio: _init called
initrigs4_tentec: _init called
initrigs4_kachina: _init called
initrigs4_tapr: _init called
initrigs4_flexradio called
initrigs4_rft: _init called
initrigs4_kit: _init called
initrigs4_tuner: _init called
initrigs4_rs: _init called
initrigs4_prm80: _init called
initrigs4_dorji: _init called
initrigs4_barrett: _init called
initrigs4_barrett: _init back from rig_register
initrigs4_elad called
initrigs4_codan: _init called
initrigs4_codan: _init back from rig_register
initrigs4_gomspace: _init called
initrigs4_mds: _init called
initrigs4_mds: _init back from rig_register
initrigs4_motorola: _init called
initrigs4_commradio: _init called
rig_test_2038: enter _TIME_BITS=64, __TIMESIZE=64 testing enabled for GLIBC 2.39
rig_init: 2038 time test passed
rig_check_rig_caps: p1=0x7235469d35e0, p2=0x7235469d9b68, rig_model=0x7235469d35e0, macro_name=0x7235469d9b68
rig_init: rig_model=Hamlib NET rigctl 20240418.0
rig_init: rx_range_list1 is empty, using rx_range_list2
rig_init: rig does not have tx_range!!
netrigctl_init version 20240418.0
16:16:25.174 [DEBUG   ] [0x72351aa006c0]       [qlog.rig.driver.hamlibdrv.function.entered] => *** [virtual bool HamlibRigDrv::open():rig/drivers/HamlibRigDrv.cpp:165] 
16:16:25.174 [DEBUG   ] [0x72351aa006c0]                [qlog.rig.driver.hamlibdrv.runtime] => Waiting for Drv mutex [virtual bool HamlibRigDrv::open():rig/drivers/HamlibRigDrv.cpp:167] 
16:16:25.174 [DEBUG   ] [0x72351aa006c0]                [qlog.rig.driver.hamlibdrv.runtime] => Using Drv [virtual bool HamlibRigDrv::open():rig/drivers/HamlibRigDrv.cpp:167] 
16:16:25.175 [DEBUG   ] [0x72351aa006c0]       [qlog.rig.driver.hamlibdrv.function.entered] => *** [bool HamlibRigDrv::isRigRespOK(int, QString, bool):rig/drivers/HamlibRigDrv.cpp:952] 
16:16:25.176 [DEBUG   ] [0x72351aa006c0]    [qlog.rig.driver.hamlibdrv.function.parameters] => -6 "Rig Open Error" false [bool HamlibRigDrv::isRigRespOK(int, QString, bool):rig/drivers/HamlibRigDrv.cpp:954] 
16:16:25.176 [DEBUG   ] [0x72351aa006c0]       [qlog.rig.driver.hamlibdrv.function.entered] => *** [QString HamlibRigDrv::hamlibErrorString(int):rig/drivers/HamlibRigDrv.cpp:1075] 
16:16:25.176 [DEBUG   ] [0x72351aa006c0]    [qlog.rig.driver.hamlibdrv.function.parameters] => -6 [QString HamlibRigDrv::hamlibErrorString(int):rig/drivers/HamlibRigDrv.cpp:1077] 
16:16:25.176 [WARNING ] [0x72351aa006c0]                                    [             ] => Detail "rig_check_rig_caps: p1=0x7235469d35e0, p2=0x7235469d9b68, rig_model=0x7235469d35e0, macro_name=0x7235469d9b68\nrig_init: rig_model=Hamlib NET rigctl 20240418.0\nrig_init: rx_range_list1 is empty, using rx_range_list2\nrig_init: rig does not have tx_range!!\nnetrigctl_init version 20240418.0\nrig.c(939):rig_open entered\nrig_settings_get_path: path=/home/joelvazquez/.config/hamlib_settings\nrig_settings_load_all: opened /home/joelvazquez/.config/hamlib_settings\nrig_open: cwd=/home/joelvazquez/hamradio/Hamlib-4.5.4\nrig_open: /home/joelvazquez/hamradio/Hamlib-4.5.4/hamlib_settings No such file or directory\nrig_open: async_data_enable=0, async_data_supported=0\nrig_open: using network address 127.0.0.1:4532\nnetwork_open: TCP connect\nnetwork_open: hoststr=127.0.0.1, portstr=4532\nconnect to 127.0.0.1:4532 failed, (trying next interface): Network error 111: Connection refused\nnetwork_open: failed to connect to 127.0.0.1:4532\nrig_open: rs->comm_state==0?=0\nrig.c(1168):rig_open returning2(-6) IO error\n\nIO error\n" [QString HamlibRigDrv::hamlibErrorString(int):rig/drivers/HamlibRigDrv.cpp:1093] 
16:16:25.176 [WARNING ] [0x72351aa006c0]                [qlog.rig.driver.hamlibdrv.runtime] => "IO error\n" [QString HamlibRigDrv::hamlibErrorString(int):rig/drivers/HamlibRigDrv.cpp:1094] 
16:16:25.176 [WARNING ] [0x72351aa006c0]                                    [             ] => "IO error\n" [void Rig::__openRig():rig/Rig.cpp:321] 
16:16:25.176 [DEBUG   ] [0x72351aa006c0]                    [qlog.rig.rig.function.entered] => *** [void Rig::__closeRig():rig/Rig.cpp:344] 
16:16:25.176 [DEBUG   ] [0x72351aa006c0]       [qlog.rig.driver.hamlibdrv.function.entered] => *** [virtual HamlibRigDrv::~HamlibRigDrv():rig/drivers/HamlibRigDrv.cpp:145] 
16:16:26.002 [DEBUG   ] [0x72351aa006c0]                    [qlog.rig.rig.function.entered] => *** [void Rig::update():rig/Rig.cpp:173] 
16:16:26.003 [DEBUG   ] [0x72351aa006c0]                             [qlog.rig.rig.runtime] => Waiting for rig mutex [void Rig::update():rig/Rig.cpp:175] 
16:16:26.003 [DEBUG   ] [0x72351aa006c0]                             [qlog.rig.rig.runtime] => Updating Rig [void Rig::update():rig/Rig.cpp:182] 
16:16:26.518 [DEBUG   ] [0x7235370eda40]                    [qlog.rig.rig.function.entered] => *** [void Rig::close():rig/Rig.cpp:329] 
16:16:26.518 [DEBUG   ] [0x72351aa006c0]                    [qlog.rig.rig.function.entered] => *** [void Rig::closeImpl():rig/Rig.cpp:336] 
16:16:26.518 [DEBUG   ] [0x72351aa006c0]                             [qlog.rig.rig.runtime] => Waiting for Rig mutex [void Rig::closeImpl():rig/Rig.cpp:338] 
16:16:26.519 [DEBUG   ] [0x72351aa006c0]                             [qlog.rig.rig.runtime] => Using Rig [void Rig::closeImpl():rig/Rig.cpp:338] 
16:16:26.519 [DEBUG   ] [0x72351aa006c0]                    [qlog.rig.rig.function.entered] => *** [void Rig::__closeRig():rig/Rig.cpp:344] 
16:16:26.519 [DEBUG   ] [0x72351aa006c0]                             [qlog.rig.rig.runtime] => Driver is not active [void Rig::__closeRig():rig/Rig.cpp:348] 
16:16:27.002 [DEBUG   ] [0x72351aa006c0]                    [qlog.rig.rig.function.entered] => *** [void Rig::update():rig/Rig.cpp:173] 
16:16:27.002 [DEBUG   ] [0x72351aa006c0]                             [qlog.rig.rig.runtime] => Waiting for rig mutex [void Rig::update():rig/Rig.cpp:175] 
16:16:27.003 [DEBUG   ] [0x72351aa006c0]                             [qlog.rig.rig.runtime] => Updating Rig [void Rig::update():rig/Rig.cpp:182] 
16:16:28.002 [DEBUG   ] [0x72351aa006c0]                    [qlog.rig.rig.function.entered] => *** [void Rig::update():rig/Rig.cpp:173] 
16:16:28.003 [DEBUG   ] [0x72351aa006c0]                             [qlog.rig.rig.runtime] => Waiting for rig mutex [void Rig::update():rig/Rig.cpp:175] 
16:16:28.003 [DEBUG   ] [0x72351aa006c0]                             [qlog.rig.rig.runtime] => Updating Rig [void Rig::update():rig/Rig.cpp:182] 
^C16:16:29.002 [DEBUG   ] [0x72351aa006c0]                    [qlog.rig.rig.function.entered] => *** [void Rig::update():rig/Rig.cpp:173] 
16:16:29.003 [DEBUG   ] [0x72351aa006c0]                             [qlog.rig.rig.runtime] => Waiting for rig mutex [void Rig::update():rig/Rig.cpp:175] 
16:16:29.003 [DEBUG   ] [0x72351aa006c0]                             [qlog.rig.rig.runtime] => Updating Rig [void Rig::update():rig/Rig.cpp:182] 
`

Hope that helps!

**Comment by foldynl** [comment]
I can see just one issue - QLog is not able to connect to your RIGCTLD. Please, check if you are running rigctld with correct port and IP Address

```Network error 111: Connection refused\nnetwork_open: failed to connect to 127.0.0.1:4532```

**Comment by vazquezrodjoel** [comment]
Yes, all was ok.  I checked all the settings, they were correct.  I created another rig with same settings, same result.  I tried JTDX, it worked fine.  I tried rigctl from terminal and it was connecting fine to the remote computer, but for some reason qlog never tried to reach that.  After couple of days I downgrade hamlib, and it just started working again when I got back to qlog.  Didnt even reboot the computer.

**Comment by foldynl** [comment]
I have the same configuration, QLog is compiled from source, using hamlib 4.5.5 without any issue on Ubuntu 24.04. 

it could be caused by the fact that you have installed QLog from PPA for older Ubuntu. Check if you have the QLog PPA set to the "noble" (24.04) version after the system upgrade.

**Comment by vazquezrodjoel** [comment]
Yes, just confirmed it has it for noble. 
`-rw-r--r-- 1 root root 1778 Oct 25 15:51 foldyna-ubuntu-qlog-noble.sources`

```
/etc/apt# apt policy qlog
qlog:
  Installed: 0.39.0-1~noble
  Candidate: 0.39.0-1~noble
  Version table:
 *** 0.39.0-1~noble 500
        500 https://ppa.launchpadcontent.net/foldyna/qlog/ubuntu noble/main amd64 Packages
        100 /var/lib/dpkg/status
```
        
I actually had to readd the cource and reinstall the package after the upgrade.

**Comment by foldynl** [comment]
so what is the result, does it work for you now?

**Comment by vazquezrodjoel** [comment]
No.  I had to downgrade hamlib to 4.5.4.  After downgrading it worked right away.

**Comment by vazquezrodjoel** [comment]
Just to update, I dont know what it was, but yesterday I reinstalled the 4.5.5 version and it worked perfect this time... following the same installation directions... so nevermind. :)
