### ISSUE TITLE
Testing 0.40 - Activities Menu

### ISSUE THREAD

**Issue by aa5sh** [foldynl/QLog#505]
I've been playing with it a little this afternoon.  So far I see a bunch of good stuff and changes have been made.  One thing I noticed was missing is the renamed 'Activities Menu' option.

![image](https://github.com/user-attachments/assets/7acacbc2-4627-4e2a-96ec-9afa3afda06d)

**Comment by aa5sh** [comment]
I was looking at the pull request.  I'm guessing I may need to run those sql commands to create the table?

**Comment by aa5sh** [comment]
Ok after I ran it I still didn't notice it.  Then I just did where it is in the status bar at the bottom.

**Comment by foldynl** [comment]
I'm just writing the WIKI for this release. Yes, it's going to be a bit of a big change, but I thought it was better to move it to the status bar.
