### ISSUE TITLE
Add Propagation Mode=none (or empty) on Edit Activities Values Tab -v0.40.0

### ISSUE THREAD

**Issue by dimarmnes** [foldynl/QLog#519]
First of all, congratulations on this new release, lots of cool features added.

I defined a new layout for satellite QSOs, in which I set the radio, antenna and propagation mode to Satellite, so far everything is fine, but when I return to my main layout where I have not defined a propagation mode, in the new QSO window the Propagation mode is prefilled with the previous layout value. I think there should be an option to set the propagation mode to "none"

73, Diego LU1IDC

**Comment by foldynl** [comment]
Yes, that's true. It should be possible to return to None. Just because the inactive option doesn't mean it will None.
