### ISSUE TITLE
DXCC statistics & 60m

### ISSUE THREAD

**Issue by TecnoTalarn** [foldynl/QLog#554]
![image](https://github.com/user-attachments/assets/1b295aaa-60fb-4127-b302-2bbf37e1724a)

In the dxcc statistics the 60m does not appear. In the image you can see that I have contacts with a station on 60m but I do not have this band in the dx stats.

**Comment by aa5sh** [comment]
There is another discussion below about [this](https://github.com/foldynl/QLog/issues/538) if you want to read by short version is the DXCC Stats follow the DXCC Rules at this time where 60M is not included.

**Comment by foldynl** [comment]
I am closing the issue because it is solved in #538
