### ISSUE TITLE
Rig without CAT

### ISSUE THREAD

**Issue by DL2KI** [foldynl/QLog#57]
QLog can also be used with a rig without CAT interface. For this purpose a rig profile with Hamlib Model 1 (dummy) can be used.

It would be desirable to be able to switch the frequency range in the bandmap (when DX cluster is running) with the drop-down list in the rig widget in this mode.

Currently, the switch can only be made by clicking on a corresponding entry in the DX-Cluster widget.

**Comment by foldynl** [comment]
> Currently, the switch can only be made by clicking on a corresponding entry in the DX-Cluster widget.

You can also use a frequency box in the New QSO widget to switch the Bandmap band.

But I try to improve it.
