### ISSUE TITLE
Alert-Beep

### ISSUE THREAD

**Issue by DL2KI** [foldynl/QLog#70]
In the alert settings you can enable the 'Beep' checkbox. This sound signal is not audible here.

Could it be that the setting of an audio device is required here?

**Comment by foldynl** [comment]
The beep uses a default OS sound alert. You may have this signal turned off or muted. QLog itself does not set up a sound or sound card. The default OS sound settings are used as the audio output - tested on Ubuntu 22.04 and Window 10 and both OS generates a beep without any issue. See my sound setting below, the important part is Alert Sound setting.

![image](https://user-images.githubusercontent.com/942769/171345651-c89dd950-bcce-4f35-a3a6-61b75408ef8b.png)

**Comment by foldynl** [comment]
Hi,

I installed Kubuntu 22.04 and can confirm that the bell sound is not played. I am not an expert for KDE (Kubuntu), but the alert bell has to be enabled in `System Settings` → `Accessibility` → check `Audible bell` and define `Custom Sound`. After this setting, QLog produces the Alert bell sound as expected.

![image](https://user-images.githubusercontent.com/942769/172123247-bbcdf6cd-7f38-4f8d-b103-a67af9756b93.png)


Unfortunately, I cannot say whether it is a workaround or a common setting of KDE, or if it has an unexpected side effect. Please,could you try this setting and give me some feedback?

**Comment by DL2KI** [comment]
Hi Ladislav,

thank you very much for the hint.

Audible bell was enabled here, but not Custom Sound. After activating a 'Custom sound', the alert signal works.

According to the help texts, 'Audible bell' should be sufficient to activate the System Bell. This also works here for system messages, such as emptying the trash and other events.

Why 'Custom sound' has to be activated additionally, I can't quite understand at the moment. But it works.

Maybe such hints should be mentioned in the wiki, in a 'Troubleshooting' section.

Thanks for your effort to solve the problem. I certainly wouldn't have thought of it myself, hi.
