### ISSUE TITLE
eQSL - QSL is incorreclty handled when contains special characters - "/" etc.

### ISSUE THREAD

**Issue by foldynl** [foldynl/QLog#74]

**Comment by c-o-m-m-a-n-d-e-r-d-a-t-a** [comment]
I found that the following in the 'QSL via' field in a QSO prevented it being uploaded to QRZ when it contained semicolon characters ; as well as forward slashes /
It caused a message which read, rather cryptically: "cannot upload the qsos, missing" (or something very close).
Thanks

**Comment by foldynl** [comment]
Please, could you send me an ADIF export of the affected QSO ?

**Comment by foldynl** [comment]
Opened a new issue for it (#247) because it is not related to this issue.
