### ISSUE TITLE
New QSO - 'Prefix - Callsign - Suffix'

### ISSUE THREAD

**Issue by DL2KI** [foldynl/QLog#90]
When entering a callsign in the 'New QSO' area, the QSO table will show the previous QSO's and the existing data will be transferred to the 'New QSO' area.

Example: DD5PX

If 'DD5PX' is portable QRV in Denmark, the callsign is 'OZ/DD5PX'.

If you now enter 'OZ/DD5PX' in the 'New QSO' area, the previous QSO's with 'DD5PX' will not be displayed in the QSO table and also the existing data will not be transferred to the 'New QSO' area.

With the input form 'Prefix - Callsign - Suffix' (example: 'OZ/DD5PX/mm') therefore only the callsign should be used for the display in the QSO table and the data transfer into the 'New QSO' area.

Location specific data can then be edited there. Fixed data will be preserved.

**Comment by foldynl** [comment]
it's a good idea, but I'm not sure what should be taken from the previous QSO. 
It seems to me that only Name, QSL Via, email, not 100% sure URL (can change based on location), maybe My Notes, but also Notes can changed based on location. 

But what you are right that Prefix/Suffix should be omitted when you want do display a station Info.

**Comment by DL2KI** [comment]
First you can see if you already had QSO's with the callsign. And QSL information or information under 'My Notes' are available.

The callsign is the primary identifier. If left as it is, it is a previously unknown QSO partner that is not associated with the regular callsign. 

There are also some OM's who have their own entries in QRZ.com. See for example 'OZ/DK1DU', 'OZ/DL9LBR' or 'DL8NBM/MM'.

From my point of view this information is not unimportant. Editing the QTH parameters, add information in 'My Notes' or adding e.g. IOTA data is not a big problem.
