### ISSUE TITLE
QSO start time

### ISSUE THREAD

**Issue by DL2KI** [foldynl/QLog#93]
It is a bit difficult to handle the start time of a QSO.

If you click on a call from the bandmap, the data is transferred to the 'New QSO' area. At the same time the timer 'Time on' and 'Time off' stays at the current time.

Now it is often the case that the OM is still in the QSO and one must wait until the current QSO is finished.

When then the QSO starts, the timer 'Time on' is no longer correct and must obviously be reset with one of the buttons    ![timer1](https://user-images.githubusercontent.com/26311402/175558815-6c91cde1-06b4-490b-8e43-bf29ddc04c84.png)
must be restarted. Both buttons work here.

The buttons are small and the function is not obvious at first sight.

Would it be possible to set a short function description of the 3 timer buttons in Wicki, or to store a context help?

![timer](https://user-images.githubusercontent.com/26311402/175559171-8a5e7d9a-9684-4c9a-bc7b-617e73351cf0.png)

In CQRLog the QSO timer starts with a click in the field 'RST send', which is easier to handle, because these fields are simply bigger and easier to hit with the mouse pointer.

Maybe you can also add a short text to the buttons, like at    
![timer2](https://user-images.githubusercontent.com/26311402/175559894-eaa9f424-4ede-4983-8621-3230907a1d35.png)

and mark the symbol of the QSO start button green.

This would also make the buttons a bit larger. Space for this is available.

**Comment by foldynl** [comment]
When you start the QSO, use F8 to restart time.

I am currently preparing Wiki for next release, I will add the description of the button to it.
